Add support for Laravel Reverb (#110)
* feat: reverb command added to swool

* feat: reverb command added to FrankenPHP Alpine

* feat: WITH_REVERB added to FrankenPHP.Dockerfile

* feat: WITH_REVERB added to RoadRunner.Dockerfile

* feat: WITH_REVERB added to RoadRunner.Dockerfile

* feat: WITH_REVERB added to Swoole.Alpine.Dockerfile

* feat: WITH_REVERB added to Swoole.Dockerfile

* feat: reverb command added to frankenphp supervisor

* feat: reverb command added to roadrunner supervisor

* feat: reverb container mode added to start container

* feat: reverb supervisord added

* feat: add docs added to documentation

* Update README.md

* ref: removed duplicate user

* wip

* wip

---------

Co-authored-by: Shahghasi Adil <adil.shahghasi@gmail.com>

diff --git a/deployment/healthcheck b/deployment/healthcheck
--- a/deployment/healthcheck
+++ b/deployment/healthcheck
@@ -15,6 +15,13 @@ elif [ "${container_mode}" = "scheduler" ]; then
         echo "Healthcheck failed."
         exit 1
     fi
+elif [ "${container_mode}" = "reverb" ]; then
+    if [ "$(supervisorctl status reverb:reverb_0 | awk '{print tolower($2)}')" = "running" ]; then
+        exit 0
+    else
+        echo "Healthcheck failed."
+        exit 1
+    fi
 elif [ "${container_mode}" = "worker" ]; then
     if [ "$(supervisorctl status worker:worker_00 | awk '{print tolower($2)}')" = "running" ]; then
         exit 0
